strictness: high
test-warnings: true
doc-warnings: false

ignore-paths:
  - env
  - tests
  - build

pycodestyle:
  options:
    max-line-length: 100

pylint:
  disable:
    - super-init-not-called

mccabe:
  run: true
