name: Python analisys

on: [push, pull_request]

jobs:
  prospector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install prospector[with_everything]==1.10.3
          pip install .
      - name: Analysing the code with prospector
        run: |
          source venv/bin/activate
          prospector
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install .
      - name: Running static types with mypy
        run: |
          mypy -p flamapy
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flamapy-fm
          pip install .
          pip install pytest==5.4.3
      - name: Running test
        run: |
          python -m pytest tests/unit_tests/diagnosis_test.py::test_fastdiag_with_configuration
